name: CloneInWorkflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - uses: docker/setup-docker-action@v4
      - uses: docker/setup-buildx-action@v3

      - name: just clone repository
        run: |
          git clone https://github.com/aetos382/DockerGitContext.git
          git clone https://gitlab.eclipse.org/eclipse/asciidoc-lang/asciidoc-tck.git
          ls -laR

      - name: build-only-dockerfile
        uses: docker/build-push-action@v6
        if: always()
        with:
          file: build-only-dockerfile.dockerfile
          load: true
          tags: build-only-dockerfile:latest

      - name: build-with-additional-context-github
        uses: docker/build-push-action@v6
        if: always()
        with:
          file: build-with-additional-context.dockerfile
          build-contexts: |
            additional-context=https://github.com/aetos382/DockerGitContext.git
          load: true
          tags: build-with-additional-context-github:latest

      - name: build-with-additional-context-github2
        uses: docker/build-push-action@v6
        if: always()
        with:
          file: build-with-additional-context.dockerfile
          build-contexts: |
            additional-context=https://github.com/docker/build-push-action.git
          load: true
          tags: build-with-additional-context-github2:latest

      - name: build-with-additional-context-gitlab
        uses: docker/build-push-action@v6
        if: always()
        with:
          file: build-with-additional-context.dockerfile
          build-contexts: |
            additional-context=https://gitlab.eclipse.org/eclipse/asciidoc-lang/asciidoc-tck.git
          load: true
          tags: build-with-additional-context-gitlab:latest
